### ISSUE TITLE
Unexpected input(s) 'workdir'

### ISSUE THREAD

**Issue by bennymeade** [trymbill/cypress-slack-video-upload-action#95]
When I add the workdir input I see an error ```Unexpected input(s) 'workdir'``` as my Cypress folder is not in the root of the repo. How can I get around this?

Workflow:
```
- name: Slack Notification
        uses: trymbill/cypress-slack-video-upload-action@v1.0.0
        if: failure()
        with:
          token: ${{ secrets.SLACK_WEBHOOK }}
          channels: my-channel
          workdir: packages/web/site/cypress
```
Error:
```
0s
Warning: Unexpected input(s) 'workdir', valid inputs are ['token', 'channels']
Run trymbill/cypress-slack-video-upload-action@v1.0.0
  with:
    token: ***
    channels: my-channel
    workdir: packages/web/site/cypress
  env:
    CYPRESS_CACHE_FOLDER: /home/runner/.cache/Cypress
    TERM: xterm
Error: ENOENT: no such file or directory, lstat '/home/runner/work/company/cypress'
```

**Comment by trymbill** [comment]
Looks like you're using version `1.0.0`, but the `workdir` input wasn't added until version `1.1.0`. The readme needs to be updated to point to the newest version (`1.3.0`). Can you try changing your config to this and let me know if that does it for yoU?
```yaml
- name: Slack Notification
  uses: trymbill/cypress-slack-video-upload-action@v1.3.0
  if: failure()
  with:
    token: ${{ secrets.SLACK_WEBHOOK }}
    channels: my-channel
    workdir: packages/web/site/cypress
```
